Nowe testy
bikol/DodawanieCE-2017 pull request #7
Opened 2017-06-06 20:45 UTC by bryant231

Na podstawie kodu z pull request #6.

2017-06-06 21:42 UTC, bikol requested changes
prosze zrobic merge

2017-06-06 22:37 UTC, bryant231 commented
Merge zrobiony.

2017-06-07 21:18 UTC, bikol requested changes
niestety jeszcze raz merge, kolega był szybszy

2017-06-08 07:45 UTC, bryant231 commented
Drugi merge zrobiony.

2017-06-08 10:27 UTC, merged